name: release
on:
  push:
    branches:
      - master
jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_windows_i386.zip
          path: dist/hello-world-golang_windows_i386.zip
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_windows_x86_64.zip
          path: dist/hello-world-golang_windows_x86_64.zip
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_linux_x86_64.tar.gz
          path: dist/hello-world-golang_linux_x86_64.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_linux_i386.tar.gz
          path: dist/hello-world-golang_linux_i386.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_linux_arm64.tar.gz
          path: dist/hello-world-golang_linux_arm64.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: hello-world-golang_linux_armv6.tar.gz
          path: dist/hello-world-golang_linux_armv6.tar.gz
